LeagueOfPlots/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LeagueOfPlots.Core;
using LeagueOfPlots.Models;
using LeagueOfPlots.Models.Gallery;
using LeagueOfPlots.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LeagueOfPlots.Controllers
{
    [Authorize]
    public class GalleryController : BaseController
    {
        public GalleryController(ApplicationDbContext context, UserManager<ApplicationUser> userManager) : base(context, userManager)
        {
        }
        public const int CacheAgeSeconds = 60 * 60 * 24 * 30; // 30 days
        public IActionResult Index()
        {
            List<Album> albums = this.ApplicationDbContext.Albums.Include(x => x.CoverPhoto).ThenInclude(x => x.Content).ToList();
            Response.Headers["Cache-Control"] = $"private,max-age={CacheAgeSeconds}";
            return View(new ViewModelGallery(albums));
        }

        public async Task<IActionResult> Create(String name)
        {
            ApplicationUser currentUser = await this.UserManager.GetUserAsync(this.HttpContext.User);
            Album album = new Album(name, currentUser.UserName);
            this.ApplicationDbContext.Add(album);
            this.ApplicationDbContext.SaveChanges();
            return new RedirectResult($"~/Gallery");
        }
    }
}

LeagueOfPlots/Controllers/LadderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LeagueOfPlots.Core;
using LeagueOfPlots.Models;
using LeagueOfPlots.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LeagueOfPlots.Controllers
{
    [Authorize]
    public class LadderController : BaseController
    {
        public LadderController(ApplicationDbContext context, UserManager<ApplicationUser> userManager) : base(context, userManager)
        {
        }

        public IActionResult Index()
        {
            return this.View(new ViewModelLadder(this.ApplicationDbContext.Users.ToList()));
        }
    }
}

LeagueOfPlots/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Identity.UserManager<ApplicationUser> UserManager
@{ 
    ApplicationUser user = await UserManager.GetUserAsync(Context.User);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>@ViewData["Title"] - Les Plots</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/gallery.scss" asp-append-version="true" />
    <link rel="shortcut icon" type="image/x-icon" href="@Url.Content("~/favicon.ico")" asp-append-version="true" />
    <link href="~/css/material-kit.css?v=2.0.4" rel="stylesheet" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" asp-append-version="true" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/table.scss" asp-append-version="true" />



</head>
<style>
    body {
        background-color: var(--white);
        background: url("/img/background.jpg");
        background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>
<body>

    <nav id="mainNav" class="navbar customed navbar-color-on-scroll fixed-top navbar-expand-lg" style="padding:0px;">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-bar navbar-kebab"></span>
                <span class="navbar-toggler-bar navbar-kebab"></span>
                <span class="navbar-toggler-bar navbar-kebab"></span>
            </button>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Accueil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Ladder" asp-action="Index">Classement</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Gallery" asp-action="Index">Galerie</a>
                    </li>
                </ul>
            </div>
            <div class="signPlot">
                <h1>Les Plots</h1>
            </div>
            <div class="collapse navbar-collapse float-right"  style="margin-right:auto;margin-left:auto;">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item user-menu">
                        <a class="nav-link" style="display:contents" asp-controller="Profile" asp-action="Index">
                            <img src="~/img/avatar.png" height="40" width="40" class="user-image" alt="Image Utilisateur" />
                            <span class="d-none d-md-inline-block">@user.FirstName</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Account" asp-action="Logout">Se déconnecter</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-xl" style="padding-top:30px;">
        <main role="main" class="pb-4">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Plots Official Website
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/4f30f82d61.js" crossorigin="anonymous" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!--   Core JS Files   -->
    <script src="~/js/core/jquery.min.js" type="text/javascript"></script>
    <script src="~/js/core/popper.min.js" type="text/javascript"></script>
    <script src="~/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
    <script src="~/js/plugins/moment.min.js"></script>
    <!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
    <script src="~/js/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script>
    <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
    <script src="~/js/plugins/nouislider.min.js" type="text/javascript"></script>
    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
    <script src="~/js/material-kit.js?v=2.0.4" type="text/javascript"></script>
    <script>
        $(window).on('scroll', function () {
            if ($(document).scrollTop() > 20) {
                debugger;
                $(".customed").addClass('scrolled')
                $(".nav-link").addClass('scrolled-link');

            } else {
                $(".customed").removeClass('scrolled')
                $(".nav-link").removeClass('scrolled-link');
            }
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

LeagueOfPlots/Views/Shared/_LayoutNotConnected.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Les Plots</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="shortcut icon" type="image/x-icon" href="@Url.Content("~/favicon.ico")" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/loginpage.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/4f30f82d61.js" crossorigin="anonymous" asp-append-version="true"></script>

</head>
<body style="height:80vh;">
   
    @RenderBody()
  
    
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>